# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [25]:
import numpy as np

#### 2. Print your NumPy version.

In [26]:
print(np.__version__)

1.19.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [27]:
a = np.random.random((2, 3, 5))
print(a)

[[[0.18010392 0.98256204 0.07303307 0.03117994 0.88850934]
  [0.46599565 0.60312926 0.82363175 0.49544181 0.73524453]
  [0.38537642 0.38686968 0.23855572 0.53913307 0.45441768]]

 [[0.50141585 0.72029379 0.40332464 0.7476684  0.39346803]
  [0.12628134 0.07600034 0.90292164 0.04607431 0.57990894]
  [0.76365038 0.09900641 0.12858909 0.35643998 0.54738238]]]


In [28]:
a = np.random.randint(0, 100, size=(2, 3, 5))
a

array([[[88, 53, 95, 81, 87],
        [17,  8, 28, 47, 68],
        [45, 11, 87,  8, 24]],

       [[34, 91, 53,  0,  6],
        [11, 82, 32, 71, 57],
        [96,  5, 89, 90, 67]]])

In [29]:

a = np.random.rand(2,3,5);
a

array([[[0.54092604, 0.42091343, 0.28249514, 0.31167956, 0.00243528],
        [0.79174461, 0.93660803, 0.51753042, 0.65635044, 0.98198169],
        [0.59895233, 0.4728494 , 0.45357861, 0.75804553, 0.03387857]],

       [[0.76978871, 0.07360327, 0.28874227, 0.72650183, 0.91839971],
        [0.75899295, 0.0399149 , 0.45331055, 0.18235682, 0.4976814 ],
        [0.11431327, 0.07066706, 0.55455321, 0.42141216, 0.68940693]]])

#### 4. Print *a*.


In [30]:
print(a)

[[[0.54092604 0.42091343 0.28249514 0.31167956 0.00243528]
  [0.79174461 0.93660803 0.51753042 0.65635044 0.98198169]
  [0.59895233 0.4728494  0.45357861 0.75804553 0.03387857]]

 [[0.76978871 0.07360327 0.28874227 0.72650183 0.91839971]
  [0.75899295 0.0399149  0.45331055 0.18235682 0.4976814 ]
  [0.11431327 0.07066706 0.55455321 0.42141216 0.68940693]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [34]:
b= np.ones((5,2,3))

In [35]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 6. Print *b*.


In [36]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [37]:
a.size == b.size


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [16]:
# Non beacause they don't have the same shape.
np.add(a,b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [39]:
c = np.transpose(b,axes=(1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
d = np.add(a,c)
d
#It works beacause they have the same shape.

array([[[1.54092604, 1.42091343, 1.28249514, 1.31167956, 1.00243528],
        [1.79174461, 1.93660803, 1.51753042, 1.65635044, 1.98198169],
        [1.59895233, 1.4728494 , 1.45357861, 1.75804553, 1.03387857]],

       [[1.76978871, 1.07360327, 1.28874227, 1.72650183, 1.91839971],
        [1.75899295, 1.0399149 , 1.45331055, 1.18235682, 1.4976814 ],
        [1.11431327, 1.07066706, 1.55455321, 1.42141216, 1.68940693]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [43]:
print(a)


[[[0.54092604 0.42091343 0.28249514 0.31167956 0.00243528]
  [0.79174461 0.93660803 0.51753042 0.65635044 0.98198169]
  [0.59895233 0.4728494  0.45357861 0.75804553 0.03387857]]

 [[0.76978871 0.07360327 0.28874227 0.72650183 0.91839971]
  [0.75899295 0.0399149  0.45331055 0.18235682 0.4976814 ]
  [0.11431327 0.07066706 0.55455321 0.42141216 0.68940693]]]


In [44]:
print(d)
# We add one to every element in a.

[[[1.54092604 1.42091343 1.28249514 1.31167956 1.00243528]
  [1.79174461 1.93660803 1.51753042 1.65635044 1.98198169]
  [1.59895233 1.4728494  1.45357861 1.75804553 1.03387857]]

 [[1.76978871 1.07360327 1.28874227 1.72650183 1.91839971]
  [1.75899295 1.0399149  1.45331055 1.18235682 1.4976814 ]
  [1.11431327 1.07066706 1.55455321 1.42141216 1.68940693]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [45]:
e =np.multiply(a,c)
e


array([[[0.54092604, 0.42091343, 0.28249514, 0.31167956, 0.00243528],
        [0.79174461, 0.93660803, 0.51753042, 0.65635044, 0.98198169],
        [0.59895233, 0.4728494 , 0.45357861, 0.75804553, 0.03387857]],

       [[0.76978871, 0.07360327, 0.28874227, 0.72650183, 0.91839971],
        [0.75899295, 0.0399149 , 0.45331055, 0.18235682, 0.4976814 ],
        [0.11431327, 0.07066706, 0.55455321, 0.42141216, 0.68940693]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [46]:
print(a ==e);
We multiply by 1 every element in a, so the resulting array e should be equal to a.

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [49]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [50]:
print("Max: ", d_max)
print("Min: ", d_min)
print("mean: ", d_mean)

Max:  1.9819816902176433
Min:  1.0024352835034542
mean:  1.477320471154967


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [51]:
f = np.empty((2, 3, 5), dtype=np.int8);

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [52]:
it = np.nditer(d, flags=['multi_index']);
while not it.finished:
    if it[0] == d_min:
        f[it.multi_index] = 0;
    elif it[0] > d_min and it[0] < d_mean:
        f[it.multi_index] = 25;
    elif it[0] == d_mean:
        f[it.multi_index] = 50;
    elif it[0] > d_mean and it[0] < d_max:
        f[it.multi_index] = 75;
    else:
        f[it.multi_index] = 100;
    it.iternext()

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [53]:
print(d)
print(f)

[[[1.54092604 1.42091343 1.28249514 1.31167956 1.00243528]
  [1.79174461 1.93660803 1.51753042 1.65635044 1.98198169]
  [1.59895233 1.4728494  1.45357861 1.75804553 1.03387857]]

 [[1.76978871 1.07360327 1.28874227 1.72650183 1.91839971]
  [1.75899295 1.0399149  1.45331055 1.18235682 1.4976814 ]
  [1.11431327 1.07066706 1.55455321 1.42141216 1.68940693]]]
[[[ 75  25  25  25   0]
  [ 75  75  75  75 100]
  [ 75  25  25  75  25]]

 [[ 75  25  25  75  75]
  [ 75  25  25  25  75]
  [ 25  25  75  25  75]]]


In [ ]:
# Yes

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [54]:
g = np.empty((2, 3, 5), dtype=str);
it = np.nditer(d, flags=['multi_index']);
while not it.finished:
    if it[0] == d_min:
        g[it.multi_index] = "A";
    elif it[0] > d_min and it[0] < d_mean:
        g[it.multi_index] = "B";
    elif it[0] == d_mean:
        g[it.multi_index] = "C";
    elif it[0] > d_mean and it[0] < d_max:
        g[it.multi_index] = "D";
    else:
        g[it.multi_index] = "E";
    it.iternext()

In [55]:
print(g)

[[['D' 'B' 'B' 'B' 'A']
  ['D' 'D' 'D' 'D' 'E']
  ['D' 'B' 'B' 'D' 'B']]

 [['D' 'B' 'B' 'D' 'D']
  ['D' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'B' 'D']]]
