# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources in the README.md file
- Happy learning!

In [4]:
# Import your libraries:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from pandas.plotting import parallel_coordinates
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn import datasets, ensemble


# Challenge 1 - Explore the Scikit-Learn Datasets

Before starting to work on our own datasets, let's first explore the datasets that are included in this Python library. These datasets have been cleaned and formatted for use in ML algorithms.

First, we will load the diabetes dataset. Do this in the cell below by importing the datasets and then loading the dataset  to the `diabetes` variable using the `load_diabetes()` function ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_diabetes.html)).

In [5]:
# Your code here:
diabetes = datasets.load_diabetes()

Let's explore this variable by looking at the different attributes (keys) of `diabetes`. Note that the `load_diabetes` function does not return dataframes. It returns you a Python dictionary.

In [6]:
# Your code here:
diabetes.keys()


dict_keys(['data', 'target', 'frame', 'DESCR', 'feature_names', 'data_filename', 'target_filename'])

#### The next step is to read the description of the dataset. 

Print the description in the cell below using the `DESCR` attribute of the `diabetes` variable. Read the data description carefully to fully understand what each column represents.

*Hint: If your output is ill-formatted by displaying linebreaks as `\n`, it means you are not using the `print` function.*

In [7]:
# Your code here:
print(diabetes.DESCR)


.. _diabetes_dataset:

Diabetes dataset
----------------

Ten baseline variables, age, sex, body mass index, average blood
pressure, and six blood serum measurements were obtained for each of n =
442 diabetes patients, as well as the response of interest, a
quantitative measure of disease progression one year after baseline.

**Data Set Characteristics:**

  :Number of Instances: 442

  :Number of Attributes: First 10 columns are numeric predictive values

  :Target: Column 11 is a quantitative measure of disease progression one year after baseline

  :Attribute Information:
      - age     age in years
      - sex
      - bmi     body mass index
      - bp      average blood pressure
      - s1      tc, T-Cells (a type of white blood cells)
      - s2      ldl, low-density lipoproteins
      - s3      hdl, high-density lipoproteins
      - s4      tch, thyroid stimulating hormone
      - s5      ltg, lamotrigine
      - s6      glu, blood sugar level

Note: Each of these 10 feature va

#### Based on the data description, answer the following questions:

1. How many attributes are there in the data? What do they mean?

1. What is the relation between `diabetes['data']` and `diabetes['target']`?

1. How many records are there in the data?

#### Now explore what are contained in the *data* portion as well as the *target* portion of `diabetes`. 

Scikit-learn typically takes in 2D numpy arrays as input (though pandas dataframes are also accepted). Inspect the shape of `data` and `target`. Confirm they are consistent with the data description.

In [9]:
# Your code here:
diabetes['data']

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [11]:
diabetes['data'].shape

(442, 10)

In [10]:
diabetes['target']

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [12]:
diabetes['target'].shape

(442,)

# Challenge 2 - Perform Supervised Learning on the Dataset

The data have already been split to predictor (*data*) and response (*target*) variables. Given this information, we'll apply what we have previously learned about linear regression and apply the algorithm to the diabetes dataset.

#### Let's briefly revisit the linear regression formula:

```
y = β0 + β1X1 + β2X2 + ... + βnXn + ϵ
```

...where:

- X1-Xn: data 
- β0: intercept 
- β1-βn: coefficients 
- ϵ: error (cannot explained by model)
- y: target

Also take a look at the `sklearn.linear_model.LinearRegression` [documentation](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html).

#### In the cell below, import the `linear_model` class from `sklearn`. 

In [13]:
# Your code here:
from sklearn.linear_model import LinearRegression


#### Create a new instance of the linear regression model and assign the new instance to the variable `diabetes_model`.

In [15]:
# Your code here:
diabetes_data=diabetes['data']
diabetes_target=diabetes['target']

#### Next, let's split the training and test data.

Define `diabetes_data_train`, `diabetes_target_train`, `diabetes_data_test`, and `diabetes_target_test`. Use the last 20 records for the test data and the rest for the training data.

In [16]:
# Your code here:
# Split the data into training/testing sets
diabetes_data_train = diabetes_data[:-20]
diabetes_data_test = diabetes_data[-20:]

#Split the target into training/testing sets
diabetes_target_train = diabetes_target[:-20]
diabetes_target_test = diabetes_target[-20:]

Fit the training data and target to `diabetes_model`. Print the *intercept* and *coefficients* of the model.

In [29]:
# Your code here:

diabetes_model = LinearRegression()
diabetes_model.fit(diabetes_data_train, diabetes_target_train)
prediction= diabetes_model.predict(diabetes_data_test)
print(diabetes_model.intercept_)
print(diabetes_model.coef_)



152.76430691633442
[ 3.03499549e-01 -2.37639315e+02  5.10530605e+02  3.27736980e+02
 -8.14131709e+02  4.92814588e+02  1.02848452e+02  1.84606489e+02
  7.43519617e+02  7.60951722e+01]


In [30]:
from sklearn.metrics import mean_squared_error, r2_score
# The coefficients
print("Coefficients: \n", diabetes_model.coef_)
# The mean squared error
print("Mean squared error: %.2f" % mean_squared_error(diabetes_target_test, prediction ))
# The coefficient of determination: 1 is perfect prediction
print("Coefficient of determination: %.2f" % r2_score(diabetes_target_test, prediction ))

Coefficients: 
 [ 3.03499549e-01 -2.37639315e+02  5.10530605e+02  3.27736980e+02
 -8.14131709e+02  4.92814588e+02  1.02848452e+02  1.84606489e+02
  7.43519617e+02  7.60951722e+01]
Mean squared error: 2004.57
Coefficient of determination: 0.59


In [39]:
from statsmodels.api import OLS

OLS(diabetes_target_train, diabetes_data_train).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.512
Model:                            OLS   Adj. R-squared:                  0.500
Method:                 Least Squares   F-statistic:                     43.16
Date:                Thu, 07 Apr 2022   Prob (F-statistic):           4.64e-58
Time:                        15:23:43   Log-Likelihood:                -2281.1
No. Observations:                 422   AIC:                             4584.
Df Residuals:                     411   BIC:                             4629.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        152.7643      2.658     57.469      0.000     147.539     157.990
x1             0.3035     61.286      0.005      0.996    -120.169     120.776
x2          -237.6393     62.837     -3.782      0.000    -361.162    -114.117
x3           510.5306     68.156      7.491      0.000     376.553     644.508
x4           327.7370     66.876      4.901      0.000     196.275     459.199
x5          -814.1317    424.044     -1.920      0.056   -1647.697      19.434
x6           492.8146    344.227      1.432      0.153    -183.850    1169.480
x7           102.8485    219.463      0.469      0.640    -328.561     534.258
x8           184.6065    167.336      1.103      0.271    -144.334     513.547
x9           743.5196    175.359      4.240      0.000     398.807    1088.232
x10           76.0952     68.293      1.114      0.266     -58.152     210.343
==============================================================================
Omnibus:                        1.544   Durbin-Watson:                   2.026
Prob(Omnibus):                  0.462   Jarque-Bera (JB):                1.421
Skew:                           0.004   Prob(JB):                        0.491
Kurtosis:                       2.716   Cond. No.                         224.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

#### Inspecting the results

From the outputs you should have seen:

- The intercept is a float number.
- The coefficients are an array containing 10 float numbers.

This is the linear regression model fitted to your training dataset.

#### Using your fitted linear regression model, predict the *y* of `diabetes_data_test`.

In [34]:
# Your code here

prediction = diabetes_model.predict(diabetes_data_test)
prediction

array([197.61846908, 155.43979328, 172.88665147, 111.53537279,
       164.80054784, 131.06954875, 259.12237761, 100.47935157,
       117.0601052 , 124.30503555, 218.36632793,  61.19831284,
       132.25046751, 120.3332925 ,  52.54458691, 194.03798088,
       102.57139702, 123.56604987, 211.0346317 ,  52.60335674])

#### Print your `diabetes_target_test` and compare with the prediction. 

In [35]:
# Your code here:
diabetes_target_test

array([233.,  91., 111., 152., 120.,  67., 310.,  94., 183.,  66., 173.,
        72.,  49.,  64.,  48., 178., 104., 132., 220.,  57.])

#### Is `diabetes_target_test` exactly the same as the model prediction? Explain.

# Bonus Challenge 1 - Hypothesis Testing with `statsmodels`

After generating the linear regression model from the dataset, you probably wonder: then what? What is the statistical way to know if my model is reliable or not?

Good question. We'll discuss that using Scikit-Learn in Challenge 5. But for now, let's use a fool-proof way by using the ([Linear Regression class of StatsModels](https://www.statsmodels.org/dev/regression.html)) which can also conduct linear regression analysis plus much more such as calcuating the F-score of the linear model as well as the standard errors and t-scores for each coefficient. The F-score and t-scores will tell you whether you can trust your linear model.

To understand the statistical meaning of conducting hypothesis testing (e.g. F-test, t-test) for slopes, read [this webpage](https://onlinecourses.science.psu.edu/stat501/node/297/) at your leisure time. We'll give you a brief overview next.

* The F-test of your linear model is to verify whether at least one of your coefficients is significantly different from zero. Translating that into the *null hypothesis* and *alternative hypothesis*, that is:

    ```
    H0 : β1 = β2 = ... = β10 = 0
    HA : At least one βj ≠ 0 (for j = 1, 2, ..., 10)
    ```

* The t-tests on each coefficient is to check whether the confidence interval for the variable contains zero. If the confidence interval contains zero, it means the null hypothesis for that variable is not rejected. In other words, this particular vaiable is not contributing to your linear model and you can remove it from your formula.

Read the documentations of [StatsModels Linear Regression](https://www.statsmodels.org/dev/regression.html) as well as its [`OLS` class](https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLS.html) which stands for *ordinary least squares*.

#### In the next cell, analyze `diabetes_data_train` and `diabetes_target_train` with the linear regression model of `statsmodels`. Print the fit summary.

Your output should look like:

![statsmodels regression](../images/statsmodels.png)

In [38]:
# Your code here:
import statsmodels.api as sm

# Fit and summarize OLS model
diabetes_data_train = sm.add_constant(diabetes_data_train)
mod = sm.OLS(diabetes_target_train, diabetes_data_train)

res = mod.fit()

print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.512
Model:                            OLS   Adj. R-squared:                  0.500
Method:                 Least Squares   F-statistic:                     43.16
Date:                Thu, 07 Apr 2022   Prob (F-statistic):           4.64e-58
Time:                        15:22:32   Log-Likelihood:                -2281.1
No. Observations:                 422   AIC:                             4584.
Df Residuals:                     411   BIC:                             4629.
Df Model:                          10                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        152.7643      2.658     57.469      0.0

#### Interpreting hypothesis testing results

Answer the following questions in the cell below:

1. What is the F-score of your linear model and is the null hypothesis rejected?

1. Does any of the t-tests of the coefficients produce a confidence interval containing zero? What are they?

1. How will you modify your linear reguression model according to the test results above?

# Challenge 3 - Peform Supervised Learning on a Pandas Dataframe

Now that we have dealt with data that has been formatted for scikit-learn, let's look at data that we will need to format ourselves.

In the next cell, load the `auto-mpg.csv` file included in this folder and assign it to a variable called `auto`.

In [40]:
# Your code here:
auto = pd.read_csv(r"C:\Users\rana_\IronhackDA\DAFT_212\module_3\Lab_7_Supervised-Sklearn\data\auto-mpg.csv")

Look at the first 5 rows using the `head()` function:

In [41]:
# Your code here:
auto.head(5)

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0  18.0          8         307.0        130.0    3504          12.0   
1  15.0          8         350.0        165.0    3693          11.5   
2  18.0          8         318.0        150.0    3436          11.0   
3  16.0          8         304.0        150.0    3433          12.0   
4  17.0          8         302.0        140.0    3449          10.5   

   model_year                       car_name  
0          70  \t"chevrolet chevelle malibu"  
1          70          \t"buick skylark 320"  
2          70         \t"plymouth satellite"  
3          70              \t"amc rebel sst"  
4          70                \t"ford torino"

Evaluate the data to ensure that all numeric columns are correctly detected as such by pandas. If a column is misclassified as object, coerce it to numeric.

In [42]:
# Your code here:
auto.dtypes

mpg             float64
cylinders         int64
displacement    float64
horse_power     float64
weight            int64
acceleration    float64
model_year        int64
car_name         object
dtype: object

What is the newest model year and the oldest model year?

In [44]:
# Your code here:
auto['model_year'].min()

70

In [45]:
auto['model_year'].max()

82

Check the dataset for missing values and remove all rows containing at least one missing value.

In [46]:
# Your code here:
auto.isna().sum()

mpg             0
cylinders       0
displacement    0
horse_power     6
weight          0
acceleration    0
model_year      0
car_name        0
dtype: int64

In [47]:
auto= auto.dropna()
auto

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0    18.0          8         307.0        130.0    3504          12.0   
1    15.0          8         350.0        165.0    3693          11.5   
2    18.0          8         318.0        150.0    3436          11.0   
3    16.0          8         304.0        150.0    3433          12.0   
4    17.0          8         302.0        140.0    3449          10.5   
..    ...        ...           ...          ...     ...           ...   
393  27.0          4         140.0         86.0    2790          15.6   
394  44.0          4          97.0         52.0    2130          24.6   
395  32.0          4         135.0         84.0    2295          11.6   
396  28.0          4         120.0         79.0    2625          18.6   
397  31.0          4         119.0         82.0    2720          19.4   

     model_year                       car_name  
0            70  \t"chevrolet chevelle malibu"  
1            70          \t"buick skylark 320"  
2            70         \t"plymouth satellite"  
3            70              \t"amc rebel sst"  
4            70                \t"ford torino"  
..          ...                            ...  
393          82            \t"ford mustang gl"  
394          82                  \t"vw pickup"  
395          82              \t"dodge rampage"  
396          82                \t"ford ranger"  
397          82                 \t"chevy s-10"  

[392 rows x 8 columns]

Find the frequency table for the `cylinders` column using the `value_counts()` function. How many possible values of cylinders are there?

In [50]:
# Your code here:
auto['cylinders'].value_counts()

4    199
8    103
6     83
3      4
5      3
Name: cylinders, dtype: int64

We would like to generate a linear regression model that will predict mpg. To do this, first drop the `car_name` column since it does not contain any quantitative data. Next separate the dataframe to predictor and response variables. Separate those into test and training data with 80% of the data in the training set and the remainder in the test set. 

Assign the predictor and response training data to `X_train` and `y_train` respectively. Similarly, assign the predictor and response test data to `X_test` and `y_test`.

*Hint: To separate data for training and test, use the `train_test_split` method we used in previous labs.*

In [51]:
#mpg mille per gallon
# Your code here:
auto.drop(['car_name'], axis = 1, inplace = True)

In [52]:
auto

mpg  cylinders  displacement  horse_power  weight  acceleration  \
0    18.0          8         307.0        130.0    3504          12.0   
1    15.0          8         350.0        165.0    3693          11.5   
2    18.0          8         318.0        150.0    3436          11.0   
3    16.0          8         304.0        150.0    3433          12.0   
4    17.0          8         302.0        140.0    3449          10.5   
..    ...        ...           ...          ...     ...           ...   
393  27.0          4         140.0         86.0    2790          15.6   
394  44.0          4          97.0         52.0    2130          24.6   
395  32.0          4         135.0         84.0    2295          11.6   
396  28.0          4         120.0         79.0    2625          18.6   
397  31.0          4         119.0         82.0    2720          19.4   

     model_year  
0            70  
1            70  
2            70  
3            70  
4            70  
..          ...  
393          82  
394          82  
395          82  
396          82  
397          82  

[392 rows x 7 columns]

In [54]:
x = auto.drop(['mpg'], axis=1)
y = auto['mpg']
# print(X.head())
print(x.shape)
# print(y.head())
print(y.shape)

(392, 6)
(392,)


In [55]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(313, 6)
(313,)
(79, 6)
(79,)


Now we will processed and peform linear regression on this data to predict the mpg for each vehicle. 

#### In the next cell, create an instance of the linear regression model and call it `auto_model`. Fit `auto_model` with your training data.

In [56]:
# Your code here:
x_train = sm.add_constant(x_train)
mod = sm.OLS(y_train, x_train)

res = mod.fit()

print(res.summary())

                            OLS Regression Results                            
Dep. Variable:                    mpg   R-squared:                       0.811
Model:                            OLS   Adj. R-squared:                  0.807
Method:                 Least Squares   F-statistic:                     218.4
Date:                Thu, 07 Apr 2022   Prob (F-statistic):          1.96e-107
Time:                        15:58:53   Log-Likelihood:                -832.28
No. Observations:                 313   AIC:                             1679.
Df Residuals:                     306   BIC:                             1705.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------
const          -15.0578      5.571     -2.703   

In [60]:
x_train.shape

(313, 7)

In [62]:
from sklearn import linear_model
regr = linear_model.LinearRegression()

# Train the model using the training sets
regr =regr.fit(x_train,y_train)

print(regr.intercept_)
print(regr.coef_)

-15.057758585282588
[ 0.         -0.116173    0.00101347 -0.00227634 -0.00656101  0.06173551
  0.76063644]


# Challenge 4 - Evaluate the Model

In addition to evaluating your model with F-test and t-test, you can also use the *Coefficient of Determination* (a.k.a. *r squared score*). This method does not simply tell *yes* or *no* about the model fit but instead indicates how much variation can be explained by the model. Based on the r squared score, you can decide whether to improve your model in order to obtain a better fit.

You can learn about the r squared score [here](). Its formula is:

![R Squared](../images/r-squared.png)

...where:

* yi is an actual data point.
* ŷi is the corresponding data point on the estimated regression line.

By adding the squares of the difference between all yi-ŷi pairs, we have a measure called SSE (*error sum of squares*) which is an application of the r squared score to indicate the extent to which the estimated regression model is different from the actual data. And we attribute that difference to the random error that is unavoidable in the real world. Obviously, we want the SSE value to be as small as possible.

#### In the next cell, compute the predicted *y* based on `X_train` and call it `y_pred`. Then calcualte the r squared score between `y_pred` and `y_train` which indicates how well the estimated regression model fits the training data.

*Hint: r squared score can be calculated using `sklearn.metrics.r2_score` ([documentation](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html)).*

In [63]:
# Your code here:

y_pred= regr.predict(x_train)
y_pred

array([20.95609215, 26.26333353, 22.56255838, 12.46318407, 34.74115023,
       14.9315701 , 34.11702802, 28.24073246, 23.96807779, 17.1302593 ,
       16.80037432, 26.61611355, 26.30794398, 30.98121298, 30.87528248,
       21.56210797, 17.9186156 , 20.76278751,  9.78482968, 27.80721377,
       20.2273002 ,  9.02193198, 16.9392466 ,  9.44761706, 26.94182756,
       30.89559471, 33.62331745, 35.48118328, 23.83617821, 22.99783358,
       19.92784153, 34.86631962, 32.73076784, 25.58508818, 24.44541041,
       33.03345258, 29.73872525, 19.65564792, 21.8665939 , 25.30949132,
       21.51340567, 30.19618874, 21.0390536 , 19.72002199, 34.94853571,
       24.67626203, 26.00988361, 30.27257564, 29.4691753 , 20.16148151,
       32.43933728, 30.59015328, 26.98917691, 22.01162485, 32.09549838,
       17.87589388, 27.13479377, 25.93193653, 32.43810108, 17.64219516,
       19.01086037, 15.98181995, 20.09087357, 25.34648167, 24.58532876,
       25.92034748, 29.96478919, 25.62559361,  9.20572947, 23.29

In [64]:
from sklearn.metrics import r2_score
r2_score(y_train, y_pred)

0.8107227953093896

In [69]:
x_test


cylinders  displacement  horse_power  weight  acceleration  model_year
79           4          96.0         69.0    2189          18.0          72
276          4         121.0        115.0    2795          15.7          78
248          4          91.0         60.0    1800          16.4          78
56           4          91.0         70.0    1955          20.5          71
393          4         140.0         86.0    2790          15.6          82
..         ...           ...          ...     ...           ...         ...
366          6         225.0         85.0    3465          16.6          81
83           4          98.0         80.0    2164          15.0          72
115          8         350.0        145.0    4082          13.0          73
3            8         304.0        150.0    3433          12.0          70
18           4          97.0         88.0    2130          14.5          70

[79 rows x 6 columns]

In [71]:
x_train['const'].value_counts()

1.0    313
Name: const, dtype: int64

In [84]:
x_test

cylinders  displacement  horse_power  weight  acceleration  model_year
79           4          96.0         69.0    2189          18.0          72
276          4         121.0        115.0    2795          15.7          78
248          4          91.0         60.0    1800          16.4          78
56           4          91.0         70.0    1955          20.5          71
393          4         140.0         86.0    2790          15.6          82
..         ...           ...          ...     ...           ...         ...
366          6         225.0         85.0    3465          16.6          81
83           4          98.0         80.0    2164          15.0          72
115          8         350.0        145.0    4082          13.0          73
3            8         304.0        150.0    3433          12.0          70
18           4          97.0         88.0    2130          14.5          70

[79 rows x 6 columns]

In [96]:
x_test['const']= 1.0

<ipython-input-96-66e0cae542cd>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_test['const']= 1.0


In [97]:
x_test

cylinders  displacement  horse_power  weight  acceleration  model_year  \
79           4          96.0         69.0    2189          18.0          72   
276          4         121.0        115.0    2795          15.7          78   
248          4          91.0         60.0    1800          16.4          78   
56           4          91.0         70.0    1955          20.5          71   
393          4         140.0         86.0    2790          15.6          82   
..         ...           ...          ...     ...           ...         ...   
366          6         225.0         85.0    3465          16.6          81   
83           4          98.0         80.0    2164          15.0          72   
115          8         350.0        145.0    4082          13.0          73   
3            8         304.0        150.0    3433          12.0          70   
18           4          97.0         88.0    2130          14.5          70   

     const  
79     1.0  
276    1.0  
248    1.0  
56     1.0  
393    1.0  
..     ...  
366    1.0  
83     1.0  
115    1.0  
3      1.0  
18     1.0  

[79 rows x 7 columns]

In [98]:
first_column = x_test.pop('const')

In [99]:
x_test

cylinders  displacement  horse_power  weight  acceleration  model_year
79           4          96.0         69.0    2189          18.0          72
276          4         121.0        115.0    2795          15.7          78
248          4          91.0         60.0    1800          16.4          78
56           4          91.0         70.0    1955          20.5          71
393          4         140.0         86.0    2790          15.6          82
..         ...           ...          ...     ...           ...         ...
366          6         225.0         85.0    3465          16.6          81
83           4          98.0         80.0    2164          15.0          72
115          8         350.0        145.0    4082          13.0          73
3            8         304.0        150.0    3433          12.0          70
18           4          97.0         88.0    2130          14.5          70

[79 rows x 6 columns]

In [100]:
x_test.insert(0, 'const', first_column)

In [101]:
x_test

const  cylinders  displacement  horse_power  weight  acceleration  \
79     1.0          4          96.0         69.0    2189          18.0   
276    1.0          4         121.0        115.0    2795          15.7   
248    1.0          4          91.0         60.0    1800          16.4   
56     1.0          4          91.0         70.0    1955          20.5   
393    1.0          4         140.0         86.0    2790          15.6   
..     ...        ...           ...          ...     ...           ...   
366    1.0          6         225.0         85.0    3465          16.6   
83     1.0          4          98.0         80.0    2164          15.0   
115    1.0          8         350.0        145.0    4082          13.0   
3      1.0          8         304.0        150.0    3433          12.0   
18     1.0          4          97.0         88.0    2130          14.5   

     model_year  
79           72  
276          78  
248          78  
56           71  
393          82  
..          ...  
366          81  
83           72  
115          73  
3            70  
18           70  

[79 rows x 7 columns]

#### Our next step is to evaluate the model using the test data. 

We would like to ensure that our model is not overfitting the data. This means that our model was made to fit too closely to the training data by being overly complex. If a model is overfitted, it is not generalizable to data outside the training data. In that case, we need to reduce the complexity of the model by removing certain features (variables).

In the cell below, use the model to generate the predicted values for the test data and assign them to `y_test_pred`. Compute the r squared score of the predicted `y_test_pred` and the oberserved `y_test` data.

In [102]:
y_test_pred= regr.predict(x_test)
y_test_pred

array([25.93279618, 26.29927859, 32.96548909, 26.8544302 , 29.45372581,
       29.08699476,  7.63874768, 29.23704446, 20.87736024, 28.91582943,
       12.48503673, 23.69898277, 16.41889199, 28.19668802, 22.03967916,
       30.88152399, 21.18311073, 31.64662323, 27.91649795, 29.78148169,
       19.84374006, 34.37342564, 33.99070737, 15.02368137, 28.76984129,
       25.99468114, 20.82555389, 16.63300722, 28.50008896, 23.82955469,
       12.81866721, 23.60612254, 21.36279705, 29.88377781, 11.05575113,
       34.7003572 , 10.84515757, 26.26088449, 11.58087074,  7.71809963,
       12.77118771, 27.81143288, 34.74146456, 26.49024951, 11.3582456 ,
        9.10855962, 17.66893597, 31.4355561 , 25.43286643, 30.38576336,
       11.60450412, 25.152572  , 24.52253515, 33.49442837, 28.90462724,
       17.82504408, 20.7761521 , 23.16942494, 23.10923128, 24.6273826 ,
        7.683821  , 22.9296696 , 27.33070582, 23.09519024, 28.13950034,
       28.69699507, 26.85355066, 29.61277981, 22.23472064,  9.37

In [103]:
# Your code here:

r2_score(y_test, y_test_pred)

0.7942349075428597

#### Explaining the results

The r squared scores of the training data and the test data are pretty close (0.8146 vs 0.7818). This means our model is not overfitted. However, there is still room to improve the model fit. Move on to the next challenge.

# Challenge 5 - Improve the Model Fit

While the most common way to improve the fit of a model is by using [regularization](https://datanice.github.io/machine-learning-101-what-is-regularization-interactive.html), there are other simpler ways to improve model fit. The first is to create a simpler model. The second is to increase the train sample size.

Let us start with the easier option and increase our train sample size to 90% of the data. Create a new test train split and name the new predictors and response variables `X_train09`, `X_test09`, `y_train09`, `y_test09`.

In [105]:
# Your code here:
x_train09, x_test09, y_train09, y_test09 = train_test_split(x, y, test_size=0.1, random_state=50)

print(x_train09.shape)
print(y_train09.shape)
print(x_test09.shape)
print(y_test09.shape)

(352, 6)
(352,)
(40, 6)
(40,)


Initialize a new linear regression model. Name this model `auto_model09`. Fit the model to the new sample (training) data.

In [107]:
# Your code here:
auto_model09 = linear_model.LinearRegression()

# Train the model using the training sets
auto_model09.fit(x_train09,y_train09)

print(auto_model09.intercept_)
print(auto_model09.coef_)

-15.693324764667924
[-0.5067499   0.01231293 -0.00315157 -0.00692213  0.10294037  0.77496306]


Compute the predicted values and r squared score for our new model and new sample data.

In [109]:
# Your code here:
y_pred_train_09 = auto_model09.predict(x_train09)
r2_score(y_train09, y_pred_train_09)

0.8062704543244579

Compute the r squared score for the smaller test set. Is there an improvement in the test r squared?

In [110]:
# Your code here:
y_pred_test_09 = auto_model09.predict(x_test09)
r2_score(y_test09, y_pred_test_09)

0.8250650723256958

In [ ]:
# There is an improvement

# Bonus Challenge 2 - Backward Elimination 

The main way to produce a simpler linear regression model is to reduce the number of variables used in the model. In scikit-learn, we can do this by using recursive feature elimination. You can read more about RFE [here](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.RFE.html).

In the next cell, we will import RFE

In [111]:
from sklearn.feature_selection import RFE

Follow the documentation and initialize an RFE model using the `auto_model` linear regression model. Set `n_features_to_select=3`

In [112]:
# Your code here:
rfe_selector = RFE(estimator=linear_model.LinearRegression(),n_features_to_select = 3, step = 1)

Fit the model and print the ranking

In [116]:
# Your code here:
m=rfe_selector.fit(x, y)
features = x.columns[m.get_support()]
print("Num Features: %s" % (m.n_features_))
print("Selected Features: %s" % (m.support_))
print("Feature Ranking: %s" % (m.ranking_))
features

Num Features: 3
Selected Features: [ True False False False  True  True]
Feature Ranking: [1 2 4 3 1 1]


Index(['cylinders', 'acceleration', 'model_year'], dtype='object')

Feature importance is ranked from most important (1) to least important (4). Generate a model with the three most important features. The features correspond to variable names. For example, feature 1 is `cylinders` and feature 2 is `displacement`.

Perform a test-train split on this reduced column data and call the split data `X_train_reduced`, `X_test_reduced`, `y_test_reduced`, `y_train_reduced`. Use an 80% split.

In [117]:
# Your code here:
x=x[features]

#split again, y is the same, only x change
x_train_reduced, x_test_reduced, y_train_reduced, y_test_reduced = train_test_split(x, y, test_size=0.2, random_state=42)


Generate a new model called `auto_model_reduced` and fit this model. Then proceed to compute the r squared score for the model. Did this cause an improvement in the r squared score?

In [118]:
# Your code here: 
auto_model_reduced = linear_model.LinearRegression()

# Train the model using the training sets
auto_model_reduced.fit(x_train_reduced, y_train_reduced)

print(auto_model_reduced.intercept_)
print(auto_model_reduced.coef_)


-17.446179491156006
[-3.08104753 -0.04749391  0.76994105]


In [119]:
y_test_reduced_pred = auto_model_reduced.predict(x_test_reduced)
r2_score(y_test_reduced,y_test_reduced_pred)

0.7149033079956759

#### Conclusion

You may obtain the impression from this lab that without knowing statistical methods in depth, it is difficult to make major progress in machine learning. That is correct. If you are motivated to become a data scientist, statistics is the subject you must be proficient in and there is no shortcut. 

Completing these labs is not likely to make you a data scientist. But you will have a good sense about what are there in machine learning and what are good for you. In your future career, you can choose one of the three tracks:

* Data scientists who need to be proficient in statistical methods.

* Data engineers who need to be good at programming.

* Data integration specialists who are business or content experts but also understand data and programming. This cross-disciplinary track brings together data, technology, and business and will be in high demands in the next decade.