# Challenge 1 - Tic Tac Toe

In this lab you will perform deep learning analysis on a dataset of playing [Tic Tac Toe](https://en.wikipedia.org/wiki/Tic-tac-toe).

There are 9 grids in Tic Tac Toe that are coded as the following picture shows:

![Tic Tac Toe Grids](tttboard.jpg)

In the first 9 columns of the dataset you can find which marks (`x` or `o`) exist in the grids. If there is no mark in a certain grid, it is labeled as `b`. The last column is `class` which tells you whether Player X (who always moves first in Tic Tac Toe) wins in this configuration. Note that when `class` has the value `False`, it means either Player O wins the game or it ends up as a draw.

Follow the steps suggested below to conduct a neural network analysis using Tensorflow and Keras. You will build a deep learning model to predict whether Player X wins the game or not.

## Step 1: Data Engineering

This dataset is almost in the ready-to-use state so you do not need to worry about missing values and so on. Still, some simple data engineering is needed.

1. Read `tic-tac-toe.csv` into a dataframe.
1. Inspect the dataset. Determine if the dataset is reliable by eyeballing the data.
1. Convert the categorical values to numeric in all columns.
1. Separate the inputs and output.
1. Normalize the input data.

In [1]:
# your code here
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt

# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense

In [2]:
data = pd.read_csv(r"C:\Users\rana_\IronhackDA\DAFT_212\module_3\Lab_13_Deep-Learning\tic-tac-toe.csv")
data

TL TM TR ML MM MR BL BM BR  class
0    x  x  x  x  o  o  x  o  o   True
1    x  x  x  x  o  o  o  x  o   True
2    x  x  x  x  o  o  o  o  x   True
3    x  x  x  x  o  o  o  b  b   True
4    x  x  x  x  o  o  b  o  b   True
..  .. .. .. .. .. .. .. .. ..    ...
953  o  x  x  x  o  o  o  x  x  False
954  o  x  o  x  x  o  x  o  x  False
955  o  x  o  x  o  x  x  o  x  False
956  o  x  o  o  x  x  x  o  x  False
957  o  o  x  x  x  o  o  x  x  False

[958 rows x 10 columns]

In [3]:
data['class'].value_counts()

True     626
False    332
Name: class, dtype: int64

In [4]:
data.replace('o', 1, inplace= True)
data.replace('x', -1, inplace= True)
data.replace('b', 0, inplace= True)

In [5]:
data

TL  TM  TR  ML  MM  MR  BL  BM  BR  class
0    -1  -1  -1  -1   1   1  -1   1   1   True
1    -1  -1  -1  -1   1   1   1  -1   1   True
2    -1  -1  -1  -1   1   1   1   1  -1   True
3    -1  -1  -1  -1   1   1   1   0   0   True
4    -1  -1  -1  -1   1   1   0   1   0   True
..   ..  ..  ..  ..  ..  ..  ..  ..  ..    ...
953   1  -1  -1  -1   1   1   1  -1  -1  False
954   1  -1   1  -1  -1   1  -1   1  -1  False
955   1  -1   1  -1   1  -1  -1   1  -1  False
956   1  -1   1   1  -1  -1  -1   1  -1  False
957   1   1  -1  -1  -1   1   1  -1  -1  False

[958 rows x 10 columns]

In [35]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(data['class'])
y

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [0., 1.],
       [0., 1.],
       [0., 1.]], dtype=float32)

In [11]:
data['class'].value_counts()
# 0 True
# 1 False

0.0    626
1.0    332
Name: class, dtype: int64

In [36]:
x = data.drop(['class'], axis = 1)
y = data['class']

In [37]:
# Keras specific
import keras
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf
from tensorflow.keras.utils import to_categorical

In [38]:
x_scaled = tf.keras.utils.normalize(x, axis=1)
x_scaled

TL        TM        TR        ML        MM        MR        BL  \
0   -0.333333 -0.333333 -0.333333 -0.333333  0.333333  0.333333 -0.333333   
1   -0.333333 -0.333333 -0.333333 -0.333333  0.333333  0.333333  0.333333   
2   -0.333333 -0.333333 -0.333333 -0.333333  0.333333  0.333333  0.333333   
3   -0.377964 -0.377964 -0.377964 -0.377964  0.377964  0.377964  0.377964   
4   -0.377964 -0.377964 -0.377964 -0.377964  0.377964  0.377964  0.000000   
..        ...       ...       ...       ...       ...       ...       ...   
953  0.333333 -0.333333 -0.333333 -0.333333  0.333333  0.333333  0.333333   
954  0.333333 -0.333333  0.333333 -0.333333 -0.333333  0.333333 -0.333333   
955  0.333333 -0.333333  0.333333 -0.333333  0.333333 -0.333333 -0.333333   
956  0.333333 -0.333333  0.333333  0.333333 -0.333333 -0.333333 -0.333333   
957  0.333333  0.333333 -0.333333 -0.333333 -0.333333  0.333333  0.333333   

           BM        BR  
0    0.333333  0.333333  
1   -0.333333  0.333333  
2    0.333333 -0.333333  
3    0.000000  0.000000  
4    0.377964  0.000000  
..        ...       ...  
953 -0.333333 -0.333333  
954  0.333333 -0.333333  
955  0.333333 -0.333333  
956  0.333333 -0.333333  
957 -0.333333 -0.333333  

[958 rows x 9 columns]

In [39]:
x_scaled.shape

(958, 9)

## Step 2: Build Neural Network

To build the neural network, you can refer to your own codes you wrote while following the [Deep Learning with Python, TensorFlow, and Keras tutorial](https://www.youtube.com/watch?v=wQ8BIBpya2k) in the lesson. It's pretty similar to what you will be doing in this lab.

1. Split the training and test data.
1. Create a `Sequential` model.
1. Add several layers to your model. Make sure you use ReLU as the activation function for the middle layers. Use Softmax for the output layer because each output has a single lable and all the label probabilities add up to 1.
1. Compile the model using `adam` as the optimizer and `sparse_categorical_crossentropy` as the loss function. For metrics, use `accuracy` for now.
1. Fit the training data.
1. Evaluate your neural network model with the test data.
1. Save your model as `tic-tac-toe.model`.

In [50]:
# your code here

x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.30, random_state=40)
print(x_train.shape); print(x_test.shape)


(670, 9)
(288, 9)


array([[[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]],

       [[1., 0.],
        [0., 1.]],

       ...,

       [[0., 1.],
        [1., 0.]],

       [[0., 1.],
        [1., 0.]],

       [[0., 1.],
        [1., 0.]]], dtype=float32)

In [42]:
y1_train=to_categorical(y_train)
y1_test=to_categorical(y_test)

In [43]:
model = Sequential()

model.add(Dense(500, activation='relu', input_dim=9))
model.add(Dense(100, activation='relu'))
model.add(Dense(100, activation='relu'))
model.add(Dense(2, activation='softmax'))


# Compile the model
model.compile(optimizer='adam', 
              loss='categorical_crossentropy', 
              metrics=['accuracy'])

In [44]:
x_train.shape

(670, 9)

In [45]:
y_train.shape

(670,)

In [46]:
# build the model
model.fit(x_train, y1_train, epochs=20)

Epoch 1/20
21/21 [==============================] - 1s 4ms/step - loss: 0.6161 - accuracy: 0.6881
Epoch 2/20
21/21 [==============================] - 0s 4ms/step - loss: 0.5045 - accuracy: 0.7701
Epoch 3/20
21/21 [==============================] - 0s 4ms/step - loss: 0.3747 - accuracy: 0.8418
Epoch 4/20
21/21 [==============================] - 0s 4ms/step - loss: 0.1905 - accuracy: 0.9642
Epoch 5/20
21/21 [==============================] - 0s 5ms/step - loss: 0.0645 - accuracy: 0.9866
Epoch 6/20
21/21 [==============================] - 0s 4ms/step - loss: 0.0306 - accuracy: 0.9925
Epoch 7/20
21/21 [==============================] - 0s 4ms/step - loss: 0.0128 - accuracy: 0.9985
Epoch 8/20
21/21 [==============================] - 0s 4ms/step - loss: 0.0080 - accuracy: 1.0000
Epoch 9/20
21/21 [==============================] - 0s 4ms/step - loss: 0.0042 - accuracy: 1.0000
Epoch 10/20
21/21 [==============================] - 0s 4ms/step - loss: 0.0026 - accuracy: 1.0000
Epoch 11/20
21/21 [

In [52]:
pred_test= model.predict(x_test)
scores = model.evaluate(x_test, y1_test, verbose=0)
scores

[0.01530343946069479, 0.9895833134651184]

In [53]:
print('Accuracy on test data: {} \n Error on test data: {}'.format(scores[1], 1 - scores[1]))

Accuracy on test data: 0.9895833134651184 
 Error on test data: 0.010416686534881592


In [54]:
model.save("tic-tac-toe.model")

INFO:tensorflow:Assets written to: tic-tac-toe.model\assets


## Step 3: Make Predictions

Now load your saved model and use it to make predictions on a few random rows in the test dataset. Check if the predictions are correct.

In [55]:
# your code here
mdl = tf.keras.models.load_model("tic-tac-toe.model")

In [58]:
import random
ind=[]
for i in range(9): 
    ind.append(random.randint(1, len(x_test)-1))
ind

[10, 101, 229, 175, 86, 221, 57, 143, 17]

In [61]:
x_test.iloc[86]

TL   -0.377964
TM    0.000000
TR   -0.377964
ML    0.000000
MM    0.377964
MR   -0.377964
BL    0.377964
BM    0.377964
BR   -0.377964
Name: 238, dtype: float64

In [64]:
y_prediction = model.predict(x_test.iloc[ind])
np.around(y_prediction,2)
observation 1 belonngs to the first class, as TRUE or 1 is in the first column. 
# ca vaut dire que le premier row indicate que la premiere observation est dans la premiere classe et le huiteme observation belonges 
to seconde classe


array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

## Step 4: Improve Your Model

Did your model achieve low loss (<0.1) and high accuracy (>0.95)? If not, try to improve your model.

But how? There are so many things you can play with in Tensorflow and in the next challenge you'll learn about these things. But in this challenge, let's just do a few things to see if they will help.

* Add more layers to your model. If the data are complex you need more layers. But don't use more layers than you need. If adding more layers does not improve the model performance you don't need additional layers.
* Adjust the learning rate when you compile the model. This means you will create a custom `tf.keras.optimizers.Adam` instance where you specify the learning rate you want. Then pass the instance to `model.compile` as the optimizer.
    * `tf.keras.optimizers.Adam` [reference](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam).
    * Don't worry if you don't understand what the learning rate does. You'll learn about it in the next challenge.
* Adjust the number of epochs when you fit the training data to the model. Your model performance continues to improve as you train more epochs. But eventually it will reach the ceiling and the performance will stay the same.

In [ ]:
# your code here

**Which approach(es) did you find helpful to improve your model performance?**

In [ ]:
# your answer here